### ISSUE TITLE
calling Watershed(lat, lon) returns error "Point must be in US (50 states)"

### ISSUE THREAD

**Issue by cfm25** [earthlab/streamstats#169]
* StreamStats version:
* Python version:
* Operating System:

### Description
I was trying to get the GEOJSON for a watershed

### What I Did
I executed this script in Python 27

import streamstats
from streamstats import Watershed
Watershed (lat=39.9644,lon=-106.5392 )

```
The coordinate cited above is on a stream reach in Colorado.  I got the exact grid from the StreamStats application for a test.

After running the script I got an error, telling me that the point must be in the US (50 states).

Traceback (most recent call last):
  File "C:\Users\cmoser\Desktop\watershed.py", line 6, in <module>
    Watershed(lat=39.9644,lon=-106.5392)
  File "D:\Python27\ArcGIS10.4\lib\site-packages\streamstats\watershed.py", line 30, in __init__
    self.state = utils.find_state(utils.find_address(lat=lat, lon=lon))
  File "D:\Python27\ArcGIS10.4\lib\site-packages\streamstats\utils.py", line 55, in find_address
    assert address['country'] == 'USA', 'Point must be in US (50 states)'
AssertionError: Point must be in US (50 states)

**Comment by mbjoseph** [comment]
Hi @cfm25! Thanks for opening this issue. 

I can't reproduce this locally using python 3.8. I notice you're using python 2.7, which is not supported by streamstats. 

On Python 3.8 I get the expected behavior:

```
Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:38) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
```

```python
>>> import streamstats
>>> from streamstats import Watershed
>>> Watershed (lat=39.9644,lon=-106.5392 )
Watershed object with HUC8: 14010001, containing lat/lon: (39.9644, -106.5392)
```

**Comment by cfm25** [comment]
My co-worker and I get the same error with Python 3.6.6, but I will try installing 3.8

**Comment by mbjoseph** [comment]
Interesting @cfm25 - your example runs correctly using the Binder link from the streamstats README (Python 3.7.3): https://mybinder.org/v2/gh/earthlab/streamstats/master

That makes me wonder whether this might be an installation issue. Can you provide some more detail about how you are installing streamstats? e.g., are you using a conda environment, virtualenv, etc.? Are you installing streamstats using `pip install streamstats`, or from source?

**Comment by cfm25** [comment]
OK here's the deal.  The UTIL. py file has this line:  assert address['country'] == 'USA', 'Point must be in US (50 states)'

If you change 'USA' to 'United States' it works just fine. :)

**Comment by cfm25** [comment]
Sorry, I forgot to answer your question.  I just used pip install streamstats to install to my Python environment on my local machine.

**Comment by mbjoseph** [comment]
Thanks @cfm25! That helps a lot. 

This issue may have been fixed in the development version of streamstats in this PR: https://github.com/earthlab/streamstats/pull/150/files

If you install the development version of streamstats, does the issue get solved? 

```
pip install git+https://github.com/earthlab/streamstats.git
```

If so, then I may need to re-deploy to PyPI.

**Comment by cfm25** [comment]
OK you nailed it!  I re-installed streamstats for Python 38 as you suggested above and it worked fine.  So, I consider this case closed.
