### ISSUE TITLE
Implement Watershed.available_characteristics() and Watershed.get_characteristics()

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/streamstats#25]
Both the `Watershed.available_characteristics()` and `Watershed.get_characteristics()` methods currently raise not implemented errors. 

### The `available_characteristics()` method

The `available_characteristics()` method should have no parameters (other than `self`) and return a dictionary of key value pairs, where they keys are parameter codes and the values are parameter names, e.g., 

```python
from streamstats import Watershed
shed = Watershed(40.009631, -105.242433)
shed.available_characteristics()
```

```
{'BSLDEM10M': 'Mean Basin Slope from 10m DEM',
 'CSL1085LFP': 'Stream Slope 10 and 85 Longest Flow Path',
 'DRNAREA': 'Drainage Area',
 'EL7500': 'Percent above 7500 ft',
 'ELEV': 'Mean Basin Elevation',
 'ELEVMAX': 'Maximum Basin Elevation',
 'I24H100Y': '24 Hour 100 Year Precipitation',
 'I24H2Y': '24 Hour 2 Year Precipitation',
 'I6H100Y': '6 Hour 100 Year Precipitation',
 'I6H2Y': '6 Hour 2 Year Precipitation',
 'LAT_OUT': 'Latitude of Basin Outlet',
 'LC11BARE': 'LC11BARE',
 'LC11CRPHAY': 'Percent_Crops_and_Hay_from_NLCD2011',
 'LC11DEV': 'Percent Developed from NLCD2011',
 'LC11FOREST': 'LC11FOREST',
 'LC11GRASS': 'LC11GRASS',
 'LC11IMP': 'Percent_Impervious_NLCD2011',
 'LC11SHRUB': 'LC11SHRUB',
 'LC11SNOIC': 'Percent snow and ice from NLCD 2011 class 12',
 'LC11WATER': 'LC11WATER',
 'LC11WETLND': 'LC11WETLND',
 'LFPLENGTH': 'LFP length',
 'LONG_OUT': 'Longitude of Basin Outlet',
 'MINBELEV': 'Minimum Basin Elevation',
 'OUTLETELEV': 'Elevation of Gage',
 'PRECIP': 'Mean Annual Precipitation',
 'RCN': 'Runoff-Curve Number',
 'RUNCO_CO': 'Soil Runoff Coefficient',
 'SSURGOA': 'SSURGO Percent Hydrologic Soil Type A',
 'SSURGOB': 'SSURGO Percent Hydrologic Soil Type B',
 'SSURGOC': 'SSURGO Percent Hydrologic Soil Type C',
 'SSURGOD': 'SSURGO Percent Hydrologic Soil Type D',
 'STATSCLAY': 'STATSGO Percentage of Clay Soils',
 'STORNHD': 'Percent Storage from NHD',
 'TOC': 'Time of concentration in hours'}
```

The `Watershed` class creates a list of watershed parameters upon initialization, accessed via: 

```python
shed.data['parameters']
```

There is one element per parameter, where each element is a dictionary: 

```python
shed.data['parameters'][0]
```

```
{
  "ID": 0,
  "name": "Mean Basin Slope from 10m DEM",
  "description": "Mean basin slope computed from 10 m DEM",
  "code": "BSLDEM10M",
  "unit": "percent",
  "value": 2.44
}
```

To make a dictionary of code/name pairs to be returned by `available_parameters()` you could do something like: 

```python
dict((p['code'], p['name']) for p in shed.data['parameters'])
```

### The `get_characteristics()` method

This method should return a dictionary of data associated with any valid parameter code, e.g., 

```python
shed.get_characteristics('BSLDEM10M')
```

```
{
  "ID": 0,
  "name": "Mean Basin Slope from 10m DEM",
  "description": "Mean basin slope computed from 10 m DEM",
  "code": "BSLDEM10M",
  "unit": "percent",
  "value": 2.44
}
```

Or, provided no particular parameter code, return an error with a message telling users that they need to provide a parameter code (and that a list of available parameter codes can be found with the `available_characteristics()` method). 

### Implementation checklist

- [x] Write unit tests for `available_characteristics()` and `get_characteristics()`
- [x] Write docstrings for both methods
- [x] Link to the USGS site that describes each parameter in the docstring for `available_characteristics()`: https://streamstatsags.cr.usgs.gov/ss_defs/basin_char_defs.aspx
- [x] Implement these methods

**Comment by jdiaz4302** [comment]
Methods working, now just have to do documentation/tests
