### ISSUE TITLE
Setup Sphinx Gallery

### ISSUE THREAD

**Issue by lwasser** [earthlab/streamstats#328]
@nkorinek you will need to a dd the sphinx gallery to this setup in  order to add the  little vignettes.
See earthpy for examples:
https://github.com/earthlab/earthpy/blob/main/docs/conf.py#L41

you then will want to update the dev reqs file with those extensions - look at earthpy or matplotcheck for how this is setup. get in touch with any issues

**Comment by nkorinek** [comment]
issue can be closed once https://github.com/earthlab/streamstats/pull/332 is merged!
